# Generated by Django 3.0.2 on 2020-10-01 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pribor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('category', models.CharField(max_length=128, verbose_name='Категория')),
                ('status', models.CharField(choices=[('active', 'Используется'), ('inactive', 'На консервации')], default='active', max_length=32, verbose_name='Статус')),
                ('purpose', models.CharField(blank=True, max_length=256, null=True, verbose_name='Назначение')),
                ('facility_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='Заводской номер')),
                ('produce_date', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('reestr_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='No. в ресстре')),
                ('inv_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='Инвентарный номер')),
                ('certificate_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='Номер поверки')),
                ('certificate_date', models.DateField(blank=True, null=True, verbose_name='Дата поверки')),
                ('certificate_place', models.CharField(blank=True, max_length=64, null=True, verbose_name='Место поверки')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='Дата очередной поверки')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='Примечание')),
                ('limit', models.CharField(blank=True, max_length=128, null=True, verbose_name='Диапазон')),
                ('sensitivity', models.CharField(blank=True, max_length=128, null=True, verbose_name='Чувствительность')),
                ('accuracy', models.CharField(blank=True, max_length=128, null=True, verbose_name='Погрешность')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolPribor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(default=0, verbose_name='Вид записи')),
                ('ref_pribor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.Pribor', verbose_name='Прибор')),
                ('ref_protocol_emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspection.Protocol', verbose_name='Протокол')),
            ],
        ),
    ]
