# Generated by Django 3.2.3 on 2021-05-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolpribor',
            name='ref_protocol_emp',
        ),
        migrations.AddField(
            model_name='pribor',
            name='unique_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Уникальный идентификатор'),
        ),
    ]
