# Generated by Django 3.0.2 on 2020-02-07 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_department_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('unread', models.BooleanField(default=True, verbose_name='Новое')),
                ('topic', models.CharField(max_length=200, verbose_name='Тема')),
                ('body', models.TextField(max_length=1024, verbose_name='Текст сообщения')),
                ('ticket_id', models.IntegerField(blank=True, verbose_name='Номер темы')),
                ('attach', models.FileField(help_text='Прикрепите файл, если требуется...', max_length=200, upload_to='messages_attach/')),
                ('receiver_department', models.ForeignKey(blank=True, help_text='Выберите отдел получения или оставьте пустым, чтобы отправить всем', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Department')),
                ('receiver_staff', models.ForeignKey(blank=True, help_text='Выберите сотрудника-получателя или оставьте пустым, чтобы отправить всем', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
