# Generated by Django 3.0.2 on 2020-02-07 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_department_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('int_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attach',
            field=models.FileField(blank=True, help_text='Прикрепите файл, если требуется...', max_length=200, null=True, upload_to='messages_attach/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver_department',
            field=models.ForeignKey(blank=True, help_text='Выберите отдел получения или оставьте пустым, чтобы отправить всем', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Department', verbose_name='Получатель-Подразделение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver_staff',
            field=models.ForeignKey(blank=True, help_text='Выберите сотрудника-получателя или оставьте пустым, чтобы отправить всем', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_receiver', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sender', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='message',
            name='ticket_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер темы'),
        ),
    ]
