# Generated by Django 3.0.3 on 2020-02-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('int_messages', '0002_auto_20200207_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
