# Generated by Django 3.0.2 on 2020-02-10 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_department_description'),
        ('int_messages', '0003_message_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('receiver_position', models.CharField(blank=True, max_length=128, null=True, verbose_name='Должность')),
                ('unread', models.BooleanField(default=True, verbose_name='Новое')),
                ('topic', models.CharField(max_length=200, verbose_name='Тема')),
                ('body', models.TextField(max_length=1024, verbose_name='Текст сообщения')),
                ('closed', models.BooleanField(default=False)),
                ('receiver_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Department', verbose_name='Получатель-Подразделение')),
            ],
        ),
    ]
