# Generated by Django 3.0.2 on 2020-10-01 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_profile_region'),
        ('int_messages', '0006_alert_alert_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='receiver_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile', verbose_name='Получатель-сотрудник'),
        ),
    ]
