# Generated by Django 3.0.3 on 2020-02-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
