# Generated by Django 3.0.3 on 2020-02-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200204_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
    ]
