# Generated by Django 3.0.3 on 2020-02-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar/images/default_avatar.jpg', height_field='60', max_length=200, upload_to='avatar/images/', width_field='60'),
        ),
    ]
