# Generated by Django 3.0.3 on 2020-02-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200204_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar/images/default_avatar.jpg', max_length=200, upload_to='avatar/images/'),
        ),
    ]
