# Generated by Django 3.0.3 on 2020-02-05 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200204_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=1024, verbose_name='Описание')),
            ],
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_view_orders', 'Profile can view ORDERS workflow'), ('can_view_laboratory', 'Profile can view laboratory functions'), ('can_view_inspection', 'Profile can view inspection activities'), ('can_view_sout', 'Profile can view SOUT activities'), ('can_view_stats', 'Profile can view statistics'), ('site_administrator', 'Profile can manage web application'))},
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Department'),
        ),
    ]
