# Generated by Django 3.0.2 on 2020-02-06 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200205_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar/images/default_avatar.jpg', max_length=200, upload_to='avatar/images/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Department', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новый'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Не_определено', 'Нет должности'), ('Делопроизводитель', 'Делопроизводитель'), ('Генеральный_директор', 'Генеральный директор'), ('Руководитель_ОИ', 'Руководитель ОИ'), ('Руководитель_ИЛ', 'Руководитель ИЛ'), ('Инженер_лаборатории', 'Инженер лаборатории'), ('Инженер_инспектор', 'Инженер инспектор')], default='Нет должности', max_length=128, verbose_name='Должность'),
        ),
    ]
