# Generated by Django 3.0.2 on 2020-04-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_initials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Не_определено', 'Нет должности'), ('Делопроизводитель', 'Делопроизводитель'), ('Генеральный_директор', 'Генеральный директор'), ('Руководитель_ОИ', 'Руководитель органа инспекции'), ('Руководитель_ИЛ', 'Руководитель ИЛ'), ('Инженер_лаборатории', 'Инженер лаборатории'), ('Инженер_инспектор', 'Инженер инспектор')], default='Не_определено', max_length=128, verbose_name='Должность'),
        ),
    ]
