# Generated by Django 2.1.4 on 2020-04-08 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200405_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_view_orders', 'Profile can view ORDERS workflow'), ('can_view_laboratory', 'Profile can view laboratory functions'), ('can_manage_devices', 'Profile can can manage with devices operations'), ('can_view_inspection', 'Profile can view inspection activities'), ('can_view_sout', 'Profile can view SOUT activities'), ('can_view_stats', 'Profile can view statistics'), ('site_administrator', 'Profile can manage web application'))},
        ),
    ]
