# Generated by Django 3.0.2 on 2020-04-13 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200408_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_view_orders', 'Profile can view ORDERS workflow'), ('can_view_laboratory', 'Profile can view laboratory functions'), ('can_manage_devices', 'Profile can can manage with devices operations'), ('can_view_inspection', 'Profile can view inspection activities'), ('can_view_sout', 'Profile can view SOUT activities'), ('can_view_stats', 'Profile can view statistics'), ('can_distribute_job', 'Profile can distribute job'), ('can_upload_rpn_files', 'Profile can UPLOAD RPN Files'), ('site_administrator', 'Profile can manage web application'))},
        ),
    ]
