# Generated by Django 3.0.2 on 2020-04-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200413_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_view_orders', 'Profile can view ORDERS workflow'), ('can_view_laboratory', 'Profile can view laboratory functions'), ('can_manage_devices', 'Profile can can manage with devices operations'), ('can_view_inspection', 'Profile can view inspection activities'), ('can_view_sout', 'Profile can view SOUT activities'), ('can_view_stats', 'Profile can view statistics'), ('can_distribute_job', 'Profile can distribute job'), ('can_upload_rpn_files', 'Profile can UPLOAD RPN Files'), ('can_search_rpn_files', 'Profile can Search RPN Files'), ('site_administrator', 'Profile can manage web application'))},
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Не_определено', 'Нет должности'), ('Делопроизводитель', 'Делопроизводитель'), ('Менеджер', 'Менеджер'), ('Генеральный_директор', 'Генеральный директор'), ('Руководитель_ОИ', 'Руководитель органа инспекции'), ('Руководитель_ИЛ', 'Руководитель ИЛ'), ('Инженер_лаборатории', 'Инженер лаборатории'), ('Инженер_инспектор', 'Инженер инспектор')], default='Не_определено', max_length=128, verbose_name='Должность'),
        ),
    ]
