# Generated by Django 3.0.7 on 2020-07-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200428_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(choices=[('Ульяновск', 'Ульяновская область'), ('Саранск', 'Республика Мордова'), ('Казань', 'Республика Татарстан'), ('Самара', 'Самарская область'), ('Пенза', 'Пензенская область')], default='Ульяновск', max_length=256, verbose_name='Регион'),
        ),
    ]
