# Generated by Django 3.0.2 on 2021-02-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_profile_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(choices=[('Ульяновск', 'Ульяновская область'), ('Саранск', 'Республика Мордова'), ('Казань', 'Республика Татарстан'), ('Самара', 'Самарская область'), ('Пенза', 'Пензенская область'), ('Саратов', 'Саратовская область')], default='Ульяновск', max_length=256, verbose_name='Регион'),
        ),
    ]
