# Generated by Django 3.2.3 on 2021-05-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210210_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Идентификатор роли'),
        ),
        migrations.AddField(
            model_name='profile',
            name='unique_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Идентификатор'),
        ),
    ]
