# Generated by Django 3.0.2 on 2020-02-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('no', models.IntegerField(verbose_name='Текущий номер')),
                ('gen_type', models.CharField(max_length=32, verbose_name='Префикс')),
                ('year', models.CharField(max_length=16, verbose_name='Год')),
                ('use_area', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Область применения')),
            ],
        ),
    ]
