# Generated by Django 3.0.2 on 2020-10-01 04:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0013_auto_20201001_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonObjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_format', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Формат проекта')),
                ('build_purpose', models.CharField(default='Новое строительство', max_length=1024, verbose_name='Цель проекта')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentLow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('see', 'Санитарно-эпидемиологическая экспертиза'), ('oos', 'Приложения к СЭЗ'), ('protocol', 'Протокол измерений ЭМП'), ('ez', 'Экспертное заключение на протокол')], max_length=128)),
                ('low_type', models.CharField(max_length=64)),
                ('low_notation', models.CharField(blank=True, max_length=128, null=True)),
                ('low_name', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('see', 'Санитарно-эпидемиологическая экспертиза'), ('oos', 'Приложения к СЭЗ'), ('protocol', 'Протокол измерений ЭМП'), ('ez', 'Экспертное заключение на протокол')], max_length=128)),
                ('sign_type', models.CharField(choices=[('approved', 'Утверждает'), ('sign', 'Подписывает')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='EvalPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, null=True, verbose_name='No.')),
                ('place', models.CharField(blank=True, max_length=256, null=True, verbose_name='Место')),
                ('no_plan', models.IntegerField(blank=True, null=True, verbose_name='No.план')),
                ('value', models.CharField(blank=True, max_length=32, null=True, verbose_name='Значение')),
                ('unit', models.CharField(default='мкВт/см2', max_length=32, verbose_name='Ед.изм')),
                ('distance', models.CharField(blank=True, max_length=16, null=True, verbose_name='Расстояние, м')),
                ('high', models.CharField(blank=True, max_length=16, null=True, verbose_name='Высота, м')),
                ('az', models.CharField(blank=True, max_length=16, null=True, verbose_name='Азимут, град')),
            ],
        ),
        migrations.CreateModel(
            name='EZ',
            fields=[
                ('ez_id', models.AutoField(primary_key=True, serialize=False)),
                ('ez_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='СЭЭ No.')),
                ('ez_date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('standard', models.CharField(blank=True, max_length=256, null=True, verbose_name='Стандарты')),
                ('freq', models.CharField(blank=True, max_length=256, null=True, verbose_name='Частоты, МГц')),
                ('az', models.CharField(blank=True, max_length=256, null=True, verbose_name='Азимуты')),
                ('szz', models.CharField(blank=True, max_length=128, null=True, verbose_name='СЗЗ (значение)')),
                ('zoz', models.CharField(blank=True, max_length=128, null=True, verbose_name='ЗОЗ (max значение)')),
                ('low', models.CharField(blank=True, max_length=128, null=True, verbose_name='Нижняя граница, м')),
                ('szz_description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Описание СЗЗ')),
                ('zoz_description', models.TextField(blank=True, max_length=2048, null=True, verbose_name='Описание ЗОЗ')),
                ('extra', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Дополнительно')),
                ('extra_staff', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Обслуживающий персонал')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=64, verbose_name='Краткое наименование')),
                ('presentation', models.CharField(max_length=512, verbose_name='Презентация')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeDocumentEZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=64, verbose_name='Краткое наименование')),
                ('presentation', models.CharField(max_length=512, verbose_name='Презентация')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_year', models.IntegerField(default=2020, verbose_name='Год ввода')),
                ('build_purpose', models.CharField(blank=True, max_length=512, null=True, verbose_name='Цель реконструкции')),
                ('name', models.CharField(max_length=1024, null=True, verbose_name='Наименование')),
                ('address', models.CharField(max_length=512, null=True, verbose_name='Адрес размещения')),
                ('has_source', models.BooleanField(default=False, verbose_name='Имеет таблицу исх. данных')),
                ('has_see', models.BooleanField(default=False, verbose_name='Имеет СЭЭ (Р1)')),
                ('has_protocol', models.BooleanField(default=False, verbose_name='Имеет протокол (Р2)')),
                ('has_ez', models.BooleanField(default=False, verbose_name='Имеет ЭЗ (Р2)')),
                ('is_shared', models.BooleanField(default=False, verbose_name='Совместное использование')),
                ('shared_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Наименование объекта')),
                ('shared_standard', models.CharField(blank=True, max_length=256, null=True, verbose_name='Стандарт')),
                ('shared_owner', models.CharField(blank=True, max_length=256, null=True, verbose_name='Совладелец')),
                ('prto_type_ref', models.ForeignKey(default='Базовая станция', on_delete=django.db.models.deletion.CASCADE, to='references.PRTOType', verbose_name='Тип ПРТО')),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('protocol_id', models.AutoField(primary_key=True, serialize=False)),
                ('protocol_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='Протокол No.')),
                ('protocol_date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('action_date', models.DateField(default=datetime.date.today, verbose_name='Дата измерения')),
                ('plan_scale', models.IntegerField(default=1000, verbose_name='Масштаб')),
                ('plan_page_count', models.IntegerField(default=1, verbose_name='Количество листов')),
                ('standard', models.CharField(blank=True, max_length=256, null=True, verbose_name='Стандарт')),
                ('ref_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.InspectionObject', verbose_name='Объект')),
            ],
        ),
        migrations.CreateModel(
            name='SEE',
            fields=[
                ('see_id', models.AutoField(primary_key=True, serialize=False)),
                ('see_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='СЭЭ No.')),
                ('see_date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('standard', models.CharField(blank=True, max_length=256, null=True, verbose_name='Стандарты')),
                ('freq', models.CharField(blank=True, max_length=256, null=True, verbose_name='Частоты, МГц')),
                ('az', models.CharField(blank=True, max_length=256, null=True, verbose_name='Азимуты')),
                ('project_header', models.TextField(blank=True, max_length=512, null=True, verbose_name='Проект')),
                ('szz', models.CharField(default='менее 0.3', max_length=128, verbose_name='СЗЗ (значение)')),
                ('unit', models.CharField(default='мкВт/см2', max_length=32, verbose_name='Ед.изм.')),
                ('low', models.CharField(default='20', max_length=128, verbose_name='Нижняя граница, м')),
                ('szz_description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Описание СЗЗ')),
                ('zoz_description', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Описание ЗОЗ')),
                ('extra', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Дополнительно')),
                ('extra_staff', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Обслуживающий персонал')),
                ('ref_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.InspectionObject', verbose_name='Объект')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneByPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('az', models.CharField(blank=True, max_length=16, null=True, verbose_name='Азимут, град')),
                ('high', models.CharField(blank=True, max_length=16, null=True, verbose_name='Высота, м')),
                ('distance', models.CharField(blank=True, max_length=16, null=True, verbose_name='Расстояние, м')),
                ('point_type', models.IntegerField(blank=True, null=True, verbose_name='Тип')),
                ('low', models.CharField(blank=True, max_length=16, null=True, verbose_name='Нижняя граница, м')),
                ('ref_see', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspection.SEE', verbose_name='СЭЭ')),
            ],
        ),
        migrations.CreateModel(
            name='SourceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_code', models.IntegerField(verbose_name='Код оборудования')),
                ('kind_description', models.CharField(blank=True, max_length=128, null=True, verbose_name='Вид оборудования')),
                ('no', models.IntegerField(blank=True, null=True, verbose_name='No.')),
                ('row_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='Тип передатчика')),
                ('power', models.CharField(blank=True, default='20', max_length=16, null=True, verbose_name='Мощность, Вт')),
                ('qty', models.IntegerField(default=1, verbose_name='Количество')),
                ('freq', models.CharField(blank=True, max_length=32, null=True, verbose_name='Частота, Гц')),
                ('modulation', models.CharField(blank=True, max_length=32, null=True, verbose_name='Модуляция')),
                ('antenna', models.CharField(blank=True, max_length=32, null=True, verbose_name='Тип антенны')),
                ('gain', models.CharField(blank=True, max_length=16, null=True, verbose_name='КУ')),
                ('high', models.CharField(blank=True, max_length=16, null=True, verbose_name='Высота')),
                ('power_fact', models.CharField(blank=True, default='20', max_length=16, null=True, verbose_name='Мощность, Вт')),
                ('dn', models.CharField(blank=True, max_length=32, null=True, verbose_name='Диаграмма')),
                ('az_hor', models.CharField(blank=True, max_length=16, null=True, verbose_name='Азимут, горизонт')),
                ('az_vert', models.CharField(blank=True, max_length=16, null=True, verbose_name='Азимут, вертикаль')),
                ('ref_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.InspectionObject', verbose_name='Объект')),
                ('ref_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.Client', verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='ResultDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('see', 'Санитарно-эпидемиологическая экспертиза'), ('oos', 'Приложения к СЭЗ'), ('protocol', 'Протокол измерений ЭМП'), ('ez', 'Экспертное заключение на протокол')], max_length=128)),
                ('attach_word', models.FileField(blank=True, help_text='Прикрепите word-документ', max_length=200, null=True, upload_to='inspection/doc_files/word/')),
                ('attach_pdf', models.FileField(blank=True, help_text='pdf-документ', max_length=200, null=True, upload_to='inspection/doc_files/pdf/')),
                ('pdf_signed', models.FileField(blank=True, help_text='Архивный документ', max_length=200, null=True, upload_to='inspection/doc_files/pdf-signed/')),
                ('ref_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.InspectionObject', verbose_name='Объект')),
            ],
        ),
        migrations.CreateModel(
            name='ProtocolPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, null=True, verbose_name='No.')),
                ('no_plan', models.IntegerField(blank=True, null=True, verbose_name='No.план')),
                ('distance', models.CharField(max_length=16, null=True, verbose_name='Расстояние, м')),
                ('value', models.CharField(max_length=32, null=True, verbose_name='Значение')),
                ('uncert', models.CharField(default='-', max_length=32, verbose_name='Неопределенность')),
                ('unit', models.CharField(default='мкВт/см2', max_length=32, verbose_name='Ед.изм')),
                ('pdu', models.CharField(default='10', max_length=32, verbose_name='Значение ПДУ')),
                ('place', models.CharField(max_length=256, null=True, verbose_name='Место')),
                ('high', models.CharField(max_length=16, null=True, verbose_name='Высота')),
                ('az', models.CharField(max_length=16, null=True, verbose_name='Азимут')),
                ('ref_protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.Protocol', verbose_name='Протокол')),
            ],
        ),
    ]
