# Generated by Django 3.2.3 on 2021-05-23 07:10

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_auto_20210523_1110'),
        ('inspection', '0002_auto_20201001_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionobject',
            name='address_fias',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='export_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата экспорта'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='export_error',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Ошибка экспорта'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='export_exclude',
            field=models.BooleanField(default=False, verbose_name='Исключить из экспорта'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='pribors',
            field=models.ManyToManyField(to='laboratory.Pribor'),
        ),
        migrations.AlterField(
            model_name='documentsign',
            name='sign_type',
            field=models.CharField(choices=[('done', 'Измеряет/Исследует'), ('approved', 'Утверждает'), ('sign', 'Подписывает')], max_length=64),
        ),
    ]
