# Generated by Django 3.0.7 on 2020-09-18 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0021_profile_region'),
        ('references', '0011_auto_20200826_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_warn_control', models.BooleanField(default=False, verbose_name='Желтый контроль включен')),
                ('is_dang_control', models.BooleanField(default=False, verbose_name='Красный контроль включен')),
                ('warn_days', models.IntegerField(blank=True, null=True, verbose_name='Дней до включения')),
                ('dang_days', models.IntegerField(blank=True, null=True, verbose_name='Дней до включения')),
                ('is_warn_alert', models.BooleanField(default=False, verbose_name='Оповещать (желтый)')),
                ('is_dang_alert', models.BooleanField(default=False, verbose_name='Оповещать (красный)')),
                ('warn_alert_type', models.IntegerField(default=1, verbose_name='Тип оповещения (желтый)')),
                ('dang_alert_type', models.IntegerField(default=1, verbose_name='Тип оповещения (красный)')),
                ('ref_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.DefaultTasks', verbose_name='Задача')),
            ],
        ),
        migrations.CreateModel(
            name='AlertPersonality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile', verbose_name='Сотрудник')),
                ('ref_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_control.ControlConfig', verbose_name='Тип контроля')),
            ],
        ),
    ]
