# Generated by Django 3.0.2 on 2020-10-01 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(default=datetime.date.today, verbose_name='Дата архивации')),
                ('doc_context', models.TextField(blank=True, max_length=8192, null=True)),
            ],
        ),
    ]
