# Generated by Django 3.0.2 on 2020-10-01 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveobject',
            name='ref_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_object', to='orders.Card', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='archiveobject',
            name='ref_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_object', to='orders.ExecutionPlan', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='archiveobject',
            name='ref_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_object', to='orders.Order', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='archiveobject',
            name='ref_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_object', to='orders.Task', verbose_name='Заявка'),
        ),
    ]
