# Generated by Django 3.0.2 on 2020-10-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionplan',
            name='ext_executor',
            field=models.CharField(blank=True, choices=[('RPN', 'Роспотребнадзор'), ('FMBA', 'ФМБА'), ('OWNER', 'Владелец ПРТО'), ('CLIENT', 'Заказчик'), ('OTHER', 'Иное')], max_length=64, null=True, verbose_name='Внешний исполнитель'),
        ),
    ]
