# Generated by Django 3.0.2 on 2021-02-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0015_contract'),
        ('orders', '0002_auto_20201001_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contracts',
            field=models.ManyToManyField(to='references.Contract'),
        ),
        migrations.AlterField(
            model_name='card',
            name='doc_title',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='order',
            name='close_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(choices=[('Ульяновск', 'Ульяновск (город и область)'), ('Димитровград', 'Димитровград'), ('Саранск', 'Саранск (Мордовия)'), ('Казань', 'Казань (Республика Татарстан)'), ('Самара', 'Самара (Самарская область)'), ('Саратов', 'Саратов (Саратовская область)'), ('Иное', 'Иное')], default='Ульяновск', max_length=200, verbose_name='Регион'),
        ),
    ]
