# Generated by Django 3.0.2 on 2020-04-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRTOType',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Наименование')),
                ('name_visible', models.CharField(max_length=512, verbose_name='Видимая часть')),
                ('pdu_staff', models.CharField(blank=True, max_length=256, null=True, verbose_name='ПДУ (персонал)')),
                ('pdu_common', models.CharField(blank=True, max_length=256, null=True, verbose_name='ПДУ (население)')),
                ('help_text', models.CharField(blank=True, max_length=512, null=True, verbose_name='Пояснение')),
            ],
        ),
    ]
