# Generated by Django 3.0.2 on 2020-05-01 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_auto_20200428_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=256, verbose_name='Центр')),
                ('full_name', models.CharField(max_length=1024, verbose_name='Регион')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='request_sign_person',
        ),
        migrations.RemoveField(
            model_name='client',
            name='request_sign_position',
        ),
        migrations.RemoveField(
            model_name='client',
            name='request_template',
        ),
        migrations.CreateModel(
            name='RequestPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_position', models.CharField(blank=True, max_length=256, null=True, verbose_name='Должность подписанта')),
                ('sign_person', models.CharField(blank=True, max_length=256, null=True, verbose_name='Заявления подписывает')),
                ('template', models.CharField(blank=True, max_length=256, null=True, verbose_name='Шаблон')),
                ('ref_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.Client', verbose_name='Заявитель')),
                ('ref_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.Region', verbose_name='Регион')),
            ],
        ),
    ]
