# Generated by Django 3.0.2 on 2020-05-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0006_auto_20200501_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestperson',
            name='regional_address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Региональный адрес'),
        ),
    ]
