# Generated by Django 3.0.2 on 2020-08-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0007_requestperson_regional_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulttasks',
            name='fill_type',
            field=models.IntegerField(choices=[(0, 'Ведомый'), (1, 'Ведущий'), (2, 'Самостоятельный')], default=2, verbose_name='Тип заполнения'),
        ),
    ]
