# Generated by Django 3.0.7 on 2020-08-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0008_defaulttasks_fill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulttasks',
            name='fill_type',
            field=models.IntegerField(default=2, verbose_name='Тип заполнения'),
        ),
    ]
