# Generated by Django 3.0.7 on 2020-08-26 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0009_defaulttasks_title_template'),
        ('references', '0009_auto_20200824_0955'),
    ]

    operations = [
    ]
