# Generated by Django 3.0.7 on 2020-08-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0010_merge_20200826_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulttasks',
            name='fill_type',
            field=models.IntegerField(choices=[(0, 'Ведомый'), (1, 'Ведущий'), (2, 'Самостоятельный')], default=2, verbose_name='Тип заполнения'),
        ),
    ]
