# Generated by Django 3.0.2 on 2020-04-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RPNLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.FileField(blank=True, help_text='Word-файл (письмо-согласование)', max_length=200, null=True, upload_to='rpn_searcher/letters/')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('orig_file_name', models.CharField(blank=True, max_length=512, null=True)),
                ('text_content', models.CharField(blank=True, max_length=8192, null=True)),
                ('file_create_date', models.DateField(blank=True, null=True, verbose_name='Дата создания файла')),
            ],
        ),
    ]
