# Generated by Django 3.0.2 on 2020-04-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpn_searcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpnletter',
            name='text_content',
            field=models.CharField(blank=True, max_length=16384, null=True),
        ),
    ]
