# Generated by Django 3.0.7 on 2020-07-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpn_searcher', '0002_auto_20200413_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpnletter',
            name='source_region',
            field=models.CharField(default='Ульяновск', max_length=256),
        ),
    ]
