# Generated by Django 3.0.2 on 2020-07-08 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpn_searcher', '0003_rpnletter_source_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpnletter',
            name='source_region',
        ),
    ]
