# Generated by Django 3.0.2 on 2020-07-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpn_searcher', '0004_remove_rpnletter_source_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpnletter',
            name='source_region',
            field=models.CharField(default='Ульяновск', max_length=256),
        ),
    ]
